# Generated by Django 4.1.7 on 2023-03-10 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_address_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='variation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.variation'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(max_length=255, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(max_length=255, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer', verbose_name='Customer Name'),
        ),
    ]
