# Generated by Django 4.1.7 on 2023-03-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_orderitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
